# Even Fibonacci numbers
'''
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

'''
########################
My first and bad aproach
########################
'''

import sys
sys.setrecursionlimit(5000000)


memory = {0: 0, 1: 1, 2: 2}


def fibo(num):
    if num in memory:
        return memory[num]
    memory[num] = fibo(num - 1) + fibo(num - 2)
    return memory[num]


def sum_even(memory):
    totalSum = 0
    for pos in memory:
        currentNum = memory.get(pos)
        if memory.get(pos) % 2 == 0:
            totalSum = totalSum + currentNum
    return totalSum


def even_fibo(num, memory):
    fibo(num)
    evenFiboSum = sum_even(memory)
    return evenFiboSum


# print(even_fibo(4000000, memory))

'''
########################
My Second try
########################
'''


def sum_even_fibo(num):
    totalSum = 0
    a = 0
    b = 1
    while b <= num:
        if b % 2 == 0:
            totalSum = totalSum + b
        a, b = b, a + b
    return totalSum


def sum_even_fibo(num):
    totalSum = 0
    a = 0
    b = 1

    while b <= num:
        # here is making the even sum
        if b % 2 == 0:
            totalSum = totalSum + b

        # here is fibo made, this time in an addition way
        a, b = b, a + b # swap variables
    return totalSum


print(sum_even_fibo(4000000))
